### ISSUE TITLE
Double key-presses in terminal if REPL only shown

### ISSUE THREAD

**Issue by willkessler** [terminalcloud/udacity-integration-demo#2] opened 2016-12-12 19:49 UTC
WHen you have the REPL only, you get two keystrokes for every key pressed.

![image](https://cloud.githubusercontent.com/assets/176268/21114302/7995bf4a-c061-11e6-8174-873ca469e9dd.png)

The branch exhibiting this behavior is _current_prod_

**Comment by reem** [comment] 2016-12-12 19:53
I believe I fixed this bug in the recent past - let me know if you are able to reproduce.

**Comment by reem** [comment] 2016-12-12 19:53
After edits: oh I see, this may be a slightly different case

**Comment by reem** [comment] 2016-12-12 20:07
Hmm, can't reproduce this on the current_prod branch. It works fine for me.

**Comment by willkessler** [comment] 2016-12-12 20:32
http://screencast.com/t/DAiYk6e4CtPA

I think the trick is to start from a totally new browser tab, clicking off the bookmarklet.html page here

https://www.terminal.com/demos/bookmarklet/bookmarklet.html

**Comment by reem** [comment] 2016-12-12 20:34
I am still unable to reproduce, can you show a video of you getting to that state? The bug itself is clear in the initial report.

**Comment by reem** [comment] 2016-12-12 22:21
Closing since we can no longer reproduce.

**Closed as completed by reem** 2016-12-12 22:21 UTC
Labels: bug
